import os
import json
from dotenv import load_dotenv
from openai import OpenAI
from src.engines.rag_engine import (
    _expand_query,
    _retrieve_and_deduplicate,
    _rerank_chunks,
    _synthesize_answer,
    chroma_client,
    embedding
)

# Loading Environment Variables:
load_dotenv()

# Initializing OpenAI Client:
openai= OpenAI(api_key= os.getenv("OPENAI_API_KEY"))

# Evaluation Dataset:
EVAL_QUESTIONS= [
{
        "query": "What are the most common complaints about delivery?",
        "collection": "customer_reviews"
    },
    {
        "query": "What is our corporate policy for handling returns after 30 days?",
        "collection": "olist_corporate_policies"
    },
    {
        "query": "Summarize the feedback from customers who bought watches.",
        "collection": "customer_reviews"
    },
    {
        "query": "What is the CEO's favorite color?", # Trick Question
        "collection": "olist_corporate_policies"
    }
]

# Evaluation Function:
def evaluate_rag_triad(user_query: str, retrieved_context: str, generated_answer: str) -> dict:
    """
    Uses LLM as a Judge to grade the RAG Triad: Context Relevance, Faithfulness, and Answer Relevance.
    :param user_query: User's query.
    :param retrieved_context: Retrieved context.
    :param generated_answer: Answer Generated by LLM.
    :return: Dictionary of RAG Triad results.
    """

    judge_prompt= f"""
    You are an expert Machine Learning QA Engineer evaluating an Advanced RAG pipeline.
    I will provide a User Query, the Retrieved Context from the database, and the AI's Generated Answer.
    
    Score the following three metrics from 1 to 10:
    1. context_relevance: Does the Retrieved Context contain the necessary information to answer the query? (Score high if the database found good data, even if the answer is bad).
    2. faithfulness: Can every single claim in the Generated Answer be traced directly back to the Retrieved Context? (Score 1 if the AI hallucinated or used outside knowledge).
    3. answer_relevance: Does the Generated Answer directly address the User Query without rambling?
    
    Output your evaluation STRICTLY as a JSON object with this exact schema:
    {{
        "context_relevance": int,
        "faithfulness": int,
        "answer_relevance": int,
        "reasoning": "A one-sentence justification for these scores."
    }}
    
    User Query: {user_query}
    
    Retrieved Context:
    {retrieved_context}
    
    Generated Answer: 
    {generated_answer}
    """

    response= openai.chat.completions.create(
        model= 'gpt-4o',
        response_format= {'type': 'json_object'},
        messages= [
            {'role': 'user', 'content': judge_prompt}
        ],
        temperature= 0.0,
    )

    return json.loads(response.choices[0].message.content)