import os
import sys
import json
from dotenv import load_dotenv
from openai import OpenAI
import pandas as pd
from datetime import datetime

# Updating Sys Path to Add project Root Folder:
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from src.utils.logger import hub_logger
from src.engines.rag_engine import (
    _expand_query,
    _retrieve_and_deduplicate,
    _rerank_chunks,
    _synthesize_answer,
    chroma_client,
    embedding
)

# Loading Environment Variables:
load_dotenv()

# Initializing OpenAI Client:
openai= OpenAI(api_key= os.getenv("OPENAI_API_KEY"))

# Evaluation Function:
def evaluate_rag_triad(user_query: str, retrieved_context: str, generated_answer: str) -> dict:
    """
    Uses LLM as a Judge to grade the RAG Triad: Context Relevance, Faithfulness, and Answer Relevance.
    :param user_query: User's query.
    :param retrieved_context: Retrieved context.
    :param generated_answer: Answer Generated by LLM.
    :return: Dictionary of RAG Triad results.
    """

    judge_prompt= f"""
    You are an expert Machine Learning QA Engineer evaluating an Advanced RAG pipeline.
    I will provide a User Query, the Retrieved Context from the database, and the AI's Generated Answer.
    
    Score the following three metrics from 1 to 10:
    1. context_relevance: Does the Retrieved Context contain the necessary information to answer the query? (Score high if the database found good data, even if the answer is bad).
    2. faithfulness: Can every single claim in the Generated Answer be traced directly back to the Retrieved Context? (Score 1 if the AI hallucinated or used outside knowledge).
    3. answer_relevance: Does the Generated Answer directly address the User Query without rambling?
    
    Output your evaluation STRICTLY as a JSON object with this exact schema:
    {{
        "context_relevance": int,
        "faithfulness": int,
        "answer_relevance": int,
        "reasoning": "A one-sentence justification for these scores."
    }}
    
    User Query: {user_query}
    Retrieved Context: {retrieved_context}
    Generated Answer: {generated_answer}
    """

    try:
        response= openai.chat.completions.create(
            model= 'gpt-4o',
            response_format= {'type': 'json_object'},
            messages= [
                {'role': 'user', 'content': judge_prompt}
            ],
            temperature= 0.0,
        )
        return json.loads(response.choices[0].message.content)

    except Exception as e:
       hub_logger.error(f"Judge Evaluation Failed: {e}")
       return {"context_relevance": 1, "faithfulness": 1, "answer_relevance": 1, "reasoning": "Failed to judge."}

def run_evaluation():
    """
    Uses Synthetic Test Dataset Generated to Measure RAG Performance.
    :return: none
    """

    # Loading Synthetic Test Dataset:
    test_path= os.path.abspath(os.path.join(os.path.dirname(__file__),'tests/rag_evaluation_set.json'))
    if not os.path.exists(test_path):
        print(f"Error: Run generate_evaluation_data.py first. Missing file: {test_path}")
        return

    with open(test_path, mode= 'r', encoding= 'utf-8') as f:
        eval_questions= json.load(f)

    print(f"Starting Comprehensive RAG Evaluation Run over {len(eval_questions)} test cases...\n")

    detailed_results= []
    summary_metrics= {
        'context_relevance': 0, 'faithfulness': 0, 'answer_relevance': 0,
        'fallback_correct': 0, 'total_fallback_cases': 0
    }

    for i, item in enumerate(eval_questions, start= 1):
        query= item['query']
        collection_name= item['collection']
        expected_truth= item.get('expected_ground_truth', "")
        is_fallback_case= (expected_truth == "OUT_OF_BOUNDS_FALLBACK")

        print(f"[{i}/{len(eval_questions)}] Evaluating Engine Collection: {collection_name}")
        print(f"  Query: '{query}'")

        try:
            collection= chroma_client.get_collection(name= collection_name,
                                                     embedding_function= embedding)
            queries= _expand_query(user_query= query)
            raw_chunks= _retrieve_and_deduplicate(search_queries= queries,
                                                  collection= collection,
                                                  chunks_per_query= 5)
            best_chunks= _rerank_chunks(user_query= query,
                                        raw_chunks= raw_chunks,
                                        top_k= 5)
            context= "\n".join([c['text'] for c in best_chunks]) if best_chunks else "NO CONTEXT FOUND"

            if not best_chunks:
                answer= 'No relevant information found'
            else:
                answer= _synthesize_answer(user_query= query,
                                           best_chunks= best_chunks,
                                           collection_name= collection_name)

            # Judging Current Answer:
            eval_scores= evaluate_rag_triad(user_query= query,
                                            retrieved_context= context,
                                            generated_answer= answer)

            # Guardrail Evaluation Tracking:
            fallback_status= 'N/A'
            if is_fallback_case:
                summary_metrics['total_fallback_cases'] += 1
                if 'No relevant information found' in answer or not best_chunks:
                    summary_metrics['fallback_correct'] += 1
                    fallback_status = 'PASSED'
                else:
                    fallback_status = 'FAILED'

            # Metrics Aggregation:
            summary_metrics['context_relevance'] += eval_scores['context_relevance']
            summary_metrics['faithfulness'] += eval_scores['faithfulness']
            summary_metrics['answer_relevance'] += eval_scores['answer_relevance']

            # Appending Structured Logs for Evaluation Dashboard:
            detailed_results.append({
                "id": i,
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "query": query,
                "collection": collection_name,
                "expected_ground_truth": expected_truth,
                "generated_answer": answer,
                "context_relevance": eval_scores['context_relevance'],
                "faithfulness": eval_scores['faithfulness'],
                "answer_relevance": eval_scores['answer_relevance'],
                "fallback_status": fallback_status,
                "reasoning": eval_scores['reasoning']
            })

            print(f" C-Rel: {eval_scores['context_relevance']}/10 | Faith: {eval_scores['faithfulness']}/10 | A-Rel: {eval_scores['answer_relevance']}/10 | OOB Fallback: {fallback_status}")

        except Exception as e:
            hub_logger.error(f"Error executing evaluation step on question {i}: {e}")
            continue

    # Computing Evaluation Summaries:
    total_runs= len(eval_questions)
    avg_c_rel= summary_metrics['context_relevance']/total_runs
    avg_faith= summary_metrics['faithfulness']/total_runs
    avg_a_rel= summary_metrics['answer_relevance']/total_runs

    fb_total= summary_metrics['total_fallback_cases']
    fb_acc= (summary_metrics['fallback_correct'] / fb_total * 100) if fb_total > 0 else 100.0

    # Printing Evaluation Summary on Terminal:
    print("\n" + "=" * 40)
    print("📋 METRIC SCORECARD REPORT")
    print("=" * 40)
    print(f"Mean Context Relevance : {avg_c_rel:.2f} / 10")
    print(f"Mean Faithfulness      : {avg_faith:.2f} / 10")
    print(f"Mean Answer Relevance  : {avg_a_rel:.2f} / 10")
    print(f"Security Guardrail Acc : {fb_acc:.1f}% ({summary_metrics['fallback_correct']}/{fb_total} OOB Traps Deflected)")
    print("=" * 40 + "\n")

    # Exporting Execution Logs:
    log_dir= os.path.abspath(os.path.join(os.path.dirname(__file__),'data/processed'))
    os.makedirs(log_dir, exist_ok=True)

    # Saving Raw Detailed Logs:
    log_file= os.path.join(log_dir, 'rag_eval_run_report.json')
    with open(log_file, 'w', encoding= 'utf-8') as f:
        json.dump(detailed_results, f, indent= 4, ensure_ascii= False)

    # Saving Metrics CSV:
    history_file= os.path.join(log_dir, 'rag_metrics.csv')
    new_eval= pd.DataFrame([{
        "execution_time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "total_test_cases": total_runs,
        "avg_context_relevance": avg_c_rel,
        "avg_faithfulness": avg_faith,
        "avg_answer_relevance": avg_a_rel,
        "guardrail_accuracy": fb_acc
    }])

    # If Metrics CSV already exists:
    if os.path.exists(history_file):
        try:
            existing_history= pd.read_csv(history_file)
            updated_history= pd.concat([existing_history, new_eval], ignore_index= True)
            updated_history.to_csv(history_file, index= False)
        except Exception:
            new_eval.to_csv(history_file, index= False)
    else:
        new_eval.to_csv(history_file, index= False)

    hub_logger.info(f"Evaluation Run files successfully stored at {log_dir}")


if __name__ == "__main__":
    run_evaluation()