import os
import json
from dotenv import load_dotenv
from openai import OpenAI
from src.engines.rag_engine import (
    _expand_query,
    _retrieve_and_deduplicate,
    _rerank_chunks,
    _synthesize_answer,
    chroma_client,
    embedding
)

# Loading Environment Variables:
load_dotenv()

# Initializing OpenAI Client:
openai= OpenAI(api_key= os.getenv("OPENAI_API_KEY"))

# Evaluation Dataset:
EVAL_QUESTIONS= [
{
        "query": "What are the most common complaints about delivery?",
        "collection": "customer_reviews"
    },
    {
        "query": "What is our corporate policy for handling returns after 30 days?",
        "collection": "olist_corporate_policies"
    },
    {
        "query": "Summarize the feedback from customers who bought watches.",
        "collection": "customer_reviews"
    },
    {
        "query": "What is the CEO's favorite color?", # Trick Question
        "collection": "olist_corporate_policies"
    }
]

# Evaluation Function:
def evaluate_rag_triad(user_query: str, retrieved_context: str, generated_answer: str) -> dict:
    """
    Uses LLM as a Judge to grade the RAG Triad: Context Relevance, Faithfulness, and Answer Relevance.
    :param user_query: User's query.
    :param retrieved_context: Retrieved context.
    :param generated_answer: Answer Generated by LLM.
    :return: Dictionary of RAG Triad results.
    """

    judge_prompt= f"""
    You are an expert Machine Learning QA Engineer evaluating an Advanced RAG pipeline.
    I will provide a User Query, the Retrieved Context from the database, and the AI's Generated Answer.
    
    Score the following three metrics from 1 to 10:
    1. context_relevance: Does the Retrieved Context contain the necessary information to answer the query? (Score high if the database found good data, even if the answer is bad).
    2. faithfulness: Can every single claim in the Generated Answer be traced directly back to the Retrieved Context? (Score 1 if the AI hallucinated or used outside knowledge).
    3. answer_relevance: Does the Generated Answer directly address the User Query without rambling?
    
    Output your evaluation STRICTLY as a JSON object with this exact schema:
    {{
        "context_relevance": int,
        "faithfulness": int,
        "answer_relevance": int,
        "reasoning": "A one-sentence justification for these scores."
    }}
    
    User Query: {user_query}
    
    Retrieved Context:
    {retrieved_context}
    
    Generated Answer: 
    {generated_answer}
    """

    response= openai.chat.completions.create(
        model= 'gpt-4o',
        response_format= {'type': 'json_object'},
        messages= [
            {'role': 'user', 'content': judge_prompt}
        ],
        temperature= 0.0,
    )

    return json.loads(response.choices[0].message.content)

if __name__ == "__main__":
    print('Starting RAG Evaluation...\n')
    metrics= {
        'context': 0,
        'faithfulness': 0,
        'answer': 0
    }
    num_questions= len(EVAL_QUESTIONS)

    for i, item in enumerate(EVAL_QUESTIONS, start= 1):
        query= item['query']
        collection_name= item['collection']
        print(f"[{i}/{num_questions}] Testing: '{query}'")

        # Executing RAG Pipeline Steps to Capture Context:
        # 1. Initializing Chroma Collection:
        collection= chroma_client.get_collection(name= collection_name,
                                                 embedding_function= embedding)
        # 2. Refining User Query:
        queries= _expand_query(user_query= query)

        # 3. Fetching Chunks using Original and Refined Queries:
        raw_chunks= _retrieve_and_deduplicate(search_queries= queries,
                                              collection= collection,
                                              chunks_per_query= 5)

        # 4. Re-Ranking Chunks:
        best_chunks= _rerank_chunks(user_query= query,
                                    raw_chunks= raw_chunks,
                                    top_k= 5)

        # Formatting Context for LLM as a Judge:
        context= "\n".join([c['text'] for c in best_chunks]) if best_chunks else "NO CONTEXT FOUND"

        # Generating Answer:
        if not best_chunks:
            answer= 'No relevant information found.'
        else:
            answer= _synthesize_answer(user_query= query,
                                       best_chunks= best_chunks,
                                       collection_name= collection_name)

        # Grading The Generated Answer:
        eval_scores= evaluate_rag_triad(user_query= query,
                                        retrieved_context= context,
                                        generated_answer= answer)
        metrics['context']+= eval_scores['context_relevance']
        metrics['faithfulness']+= eval_scores['faithfulness']
        metrics['answer']+= eval_scores['answer_relevance']

        print(f"  ↳ Context Relevance: {eval_scores['context_relevance']}/10")
        print(f"  ↳ Faithfulness:      {eval_scores['faithfulness']}/10")
        print(f"  ↳ Answer Relevance:  {eval_scores['answer_relevance']}/10")
        print(f"  ↳ Judge Notes:       {eval_scores['reasoning']}\n")

    # Final Evaluation Card:
    print("========================================")
    print("FINAL RAG SCORECARD")
    print("========================================")
    print(f"Avg Context Relevance: {metrics['context'] / num_questions:.1f} / 10")
    print(f"Avg Faithfulness:      {metrics['faithfulness'] / num_questions:.1f} / 10")
    print(f"Avg Answer Relevance:  {metrics['answer'] / num_questions:.1f} / 10")
    print("========================================\n")